### ISSUE TITLE
Adding decimal acceptance

### ISSUE THREAD

**Issue by nishtha981** [acmpesuecc/python-simple-calculator#1]
the calculator doesn't accept decimal values

**Comment by advaithas** [comment]
I would like to work on this issue

**Comment by ad1tya24** [comment]
would like to work on it

**Comment by samarth777** [comment]
can you assign this to me

**Comment by brindach** [comment]
kindly assign

**Comment by surajkadapa** [comment]
Hello can u assign me this issue

**Comment by BalajiRock** [comment]
Can I work on this -Balaji M(PES2UG21CS117)
