### ISSUE TITLE
Adding more functions like power etc

### ISSUE THREAD

**Issue by nishtha981** [acmpesuecc/python-simple-calculator#3]
25 per adding 1 function as a tab 
Make sure they don't messup the frame of the calculator
Make sure they show up on the tkinter GUI

**Comment by Devansh-Gutti** [comment]
I would like to work on this issue

**Comment by tanishkapasarad** [comment]
hey i would like to work on this issue

**Comment by DhatriC123** [comment]
can i work on this??

**Comment by Shruti1308** [comment]
can i work on this ???

**Comment by sphoorthiY** [comment]
can i work on this ???

**Comment by Ganther3301** [comment]
i would like to work on this

**Comment by sphoorthiY** [comment]
can i work on this ???
PES2UG21CS241

**Comment by nishtha981** [comment]
Right now the issue is open assignment
all of you can work on it

**Comment by ShashankPatali** [comment]
Can i work on this please? :)

**Comment by Sahana-Math** [comment]
Can you please assign this to me? 
Sahana S Math
PES2UG21CS450

**Comment by yashwanth05** [comment]
Can i work on this issue.
i already finished power function.
name:yashwanth

**Comment by DhatriC123** [comment]
@nishtha981 can i please work on this isssue?

**Comment by DhatriC123** [comment]
can i work on it...i have finished most of it already when it was open

**Comment by nishtha981** [comment]
@Sahana-Math  you can work on it 
you've been assigned

**Comment by akshatg131** [comment]
can i work on it? I have an extra function ready.

**Comment by VishalCE7** [comment]
Could you please assign me to this issue
Vishal C E 
PES2UG20CS386

**Comment by NavinShrinivas** [comment]
Assigning @VishalCE7

**Comment by VishalCE7** [comment]
Hey, im am still working on it and i think i will be done in half an hour max, i request u to let me extend for another half an hour
