### ISSUE TITLE
Change the colouring

### ISSUE THREAD

**Issue by nishtha981** [acmpesuecc/python-simple-calculator#4]
it's too gray :( 
try adding a good colour scheme

**Comment by siddarthpai** [comment]
hey could I work on this

**Comment by ankithlemuel** [comment]
can i work on this?

**Comment by AtharvaAnilChanda** [comment]
Hey , Can I work on this please ??

**Comment by nishtha981** [comment]
Right now the issue is open assignment 
all of you can work on it

**Comment by SahilPrabhu** [comment]
Hey can i work on this issue

**Comment by SwethaRanganathan** [comment]
can i work on this issue?
