### ISSUE TITLE
Removing the the small box that comes near the select button

### ISSUE THREAD

**Issue by nishtha981** [acmpesuecc/python-simple-calculator#5]
<img width="110" alt="Screenshot 2022-10-19 231900" src="https://user-images.githubusercontent.com/92522516/196766926-edc70f2c-e412-43bc-bbf6-e8af4f796f16.png">

**Comment by Ganther3301** [comment]
i would like to work on this

**Comment by nishtha981** [comment]
Right now the issue is open assignment
all of you can work on it

**Comment by Geeker357** [comment]
Hey, Can you assign me this code

**Comment by VishalS-HK** [comment]
Hey Can I work on this
?

**Comment by nishtha981** [comment]
this issue has been resolved
thank you for your time!
